name: CI

on:
  pull_request:
    branches: master

jobs:
  # Check if app successfully builds and do any unit tests..
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.18.3
      - name: Install Packages
        run: yarn install
      - name: Build project
        run: yarn build
