name: CI

on:
  push:
    branches: master

jobs:
  # Check if app successfully builds and do any unit tests..
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.18.3
      - name: Install Packages
        run: yarn install
      - name: Build project
        run: yarn build

  # Deploy image to docker hub.
  push_image:
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-actions@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.MUJIK_API_TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
